name: Daily CSV Update

# Runs every morning to append new CSV records to Poligonos_RPAS.json

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Detect and update GeoJSON
        run: python scripts/daily_csv_update.py

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add Poligonos_RPAS.json Geodatabase/last_processed_row.txt
          git commit -m "Update GeoJSON with new CSV rows" || echo "No changes"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update GeoJSON with new CSV rows"
          title: "Automated GeoJSON update"
          body: "Adds new features from updated Geodatabase.csv."
          branch: auto/daily-csv-update
