name: Actualizar GeoJSON diario

on:
  schedule:
    - cron: '0 6 * * *' # Todos los días a las 6:00 am
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHEET_ID: ${{ secrets.SHEET_ID }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar pruebas
        run: pytest

      - name: Actualizar GeoJSON
        run: python update_geojson.py

      - name: Commit y push cambios
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add Poligonos_RPAS.json
          git commit -m "Actualización automática del GeoJSON (.json)" || echo "Sin cambios"
          git push
