name: Generar GeoJSON

# Este workflow ejecuta `update_geojson.py` usando el archivo
# `Geodatabase/Geodatabase.csv` para generar el GeoJSON.

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar tests
        run: pytest
        env:
          PYTHONPATH: ${{ github.workspace }}

      - name: Actualizar GeoJSON
        run: python update_geojson.py

      - name: Sincronizar rama
        run: git pull --ff-only

      - name: Commit cambios
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add Poligonos_RPAS.json
          git commit -m "Actualización automática del GeoJSON (.json)" || echo "Sin cambios"

      - name: Crear Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Actualización automática del GeoJSON (.json)"
          title: "Actualización automática del GeoJSON"
          body: "Este PR actualiza el archivo Poligonos_RPAS.json con los datos de Geodatabase/Geodatabase.csv."
          branch: auto/update-geojson
